[package]
name = "laconia-liveness"
version = "0.1.0"
edition = "2024"

[features]
default = []
client = []
server = []

[dependencies]
prost = "0.13.5"
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"
