[package]
name = "laconia-control"
version = "0.1.0"
edition = "2024"

[dependencies]
laconia-liveness = { version = "0.1.0", path = "../laconia-liveness", features = ["server"] }
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
